sudo: required
language: php
php:
  - "5.6"
  - "7"

services:
  - mysql
  - redis-server

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS qzphp_db character set utf8mb4 collate utf8mb4_unicode_ci;'
  - mysql -e 'create table employee (id int unsigned auto_increment, name varchar(50), age int, primary key (id) );' qzphp_db
  - mysql qzphp_db < `pwd`/ci/db.sql

install:
  - composer install

before_script:
  - php ./src/QzPhp/qz.php mapper
  - cp `pwd`/ci/travis.conf `pwd`/testconf.php

script:
  - phpunit -c phpunit.xml