sudo: required
language: php
php:
  - "5.6"
  - "7"

services:
  - docker

before_install:
  - docker --version
  - docker pull mariadb:latest
  - docker run -d --name query_db -p 3307:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=true mariadb:latest
  - docker run -d --name redis_tst -p 6381:6379 redis:latest
  - sleep 25
  - docker exec query_db mysql -uroot -e "create database qzphp_db character set utf8mb4 collate utf8mb4_unicode_ci"
  - docker exec query_db mysql -uroot -e "create table employee (id int unsigned auto_increment, name varchar(50), age int, primary key (id) );" qzphp_db

install:
  - composer install

before_script:
  - php ./src/QzPhp/qz.php mapper
  - cp `pwd`/ci/travis.conf `pwd`/testconf.php

script:
  - docker run --net dckr_net -v `pwd`:/app --rm registry.gitlab.com/fendy3002/dockerfiles/qz/phpunit:latest -c phpunit.xml