sudo: required
language: php
php:
  - "5.6"
  - "7"

services:
  - docker

before_install:
  - docker --version
  - docker pull mariadb:latest
  - docker run -d --name query_db -p 3307:3306 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=testdb mariadb:latest

script:
  - phpunit